# Generated by Django 6.0.2 on 2026-02-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("fecha_compra", models.DateField()),
                ("fecha_caducidad", models.DateField()),
                ("categoria", models.CharField(max_length=50)),
                ("foto", models.ImageField(upload_to="alimentos/")),
            ],
        ),
    ]
