# Generated by Django 6.0 on 2026-02-04 01:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alimentos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="alimento",
            name="fecha_compra",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="alimento",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="alimentos/"),
        ),
        migrations.AlterField(
            model_name="alimento",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="alimentos.categoria"
            ),
        ),
    ]
