# Generated by Django 6.0 on 2026-02-04 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alimentos", "0002_categoria_alter_alimento_fecha_compra_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alimento",
            name="categoria",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="alimentos.categoria",
            ),
        ),
        migrations.AlterField(
            model_name="alimento",
            name="fecha_compra",
            field=models.DateField(),
        ),
    ]
