# Generated by Django 6.0 on 2026-02-04 02:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alimentos", "0003_alter_alimento_categoria_alter_alimento_fecha_compra"),
    ]

    operations = [
        migrations.CreateModel(
            name="Compra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("fecha_compra", models.DateField(default=datetime.date.today)),
                ("comprado", models.BooleanField(default=False)),
            ],
        ),
    ]
