# Generated by Django 6.0.2 on 2026-02-06 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alimentos", "0006_receta"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="alimento",
            name="usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alimentos",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
