# Generated by Django 6.0.2 on 2026-02-08 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alimentos", "0007_alter_alimento_usuario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receta",
            name="usuario",
        ),
        migrations.AddField(
            model_name="compra",
            name="usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compras",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
