# Generated by Django 6.0.2 on 2026-02-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alimentos", "0008_remove_receta_usuario_compra_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("FRUTAS", "🍎 Frutas y verduras"),
                    ("CARNES", "🥩 Carnes y proteínas"),
                    ("LACTEOS", "🥛 Lácteos"),
                    ("CEREALES", "🌾 Cereales y granos"),
                    ("ENLATADOS", "🥫 Enlatados y conservas"),
                    ("ESPECIAS", "🧂 Condimentos y especias"),
                    ("SNACKS", "🍪 Snacks"),
                    ("CONGELADOS", "❄️ Congelados"),
                    ("BEBIDAS", "🧃 Bebidas"),
                    ("OTROS", "📦 Otros"),
                ],
                default="OTROS",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="alimento",
            name="foto",
            field=models.ImageField(default=1, upload_to="alimentos/"),
            preserve_default=False,
        ),
    ]
